app:
  port: ${{ CLOUDWEAR_API_PORT }}

datasource:
  defalut:
    type: mysql
    host: ${{ MYSQL_HOST }}
    port: ${{ MYSQL_PORT }}
    username: ${{ MYSQL_USER }}
    password: ${{ MYSQL_PASSWORD }}
    database: ${{ MYSQL_DATABASE }}
    synchronize: false
    autoLoadEntities: true
    bigNumberStrings: false
    supportBigNumbers: true

redis:
  defalut:
    host: ${{ REDIS_HOST }}
    port: ${{ REDIS_PORT }}
    username: ${{ REDIS_USERNAME }}
    password: ${{ REDIS_PASSWORD }}
    db: 0

bull:
  redis:
    host: ${{ REDIS_HOST }}
    port: ${{ REDIS_PORT }}
    username: ${{ REDIS_USERNAME }}
    password: ${{ REDIS_PASSWORD }}
    db: 1
